export const OrderData = [
    {
        userName: "Laura Smith",
        ProductName: "Key Tag",
        Quantity: 5,
        Price: 20.3,
        date: "2013/04/23",
        Status: "Pending",
    },
    {
        userName: "Denis Michelle",
        ProductName: "Wood Work",
        Quantity: 1,
        Price:30.23 ,
        date: "2020/05/06",
        Status: "Pending"  ,
    },
    {
        userName: "Carla Russel",
        ProductName: "Paper Craft",
        Quantity: 6,
        Price: 100 ,
        date: "2020/05/06",
        Status: "Accepted",
    },
    {
        userName: "Carla Russel",
        ProductName: "Paper Craft",
        Quantity: 2,
        Price: 40.00 ,
        date: "2020/05/06",
        Status: "Rejected",
    },
    
    {
        userName: "Joe Daniel",
        ProductName: "Cushion Design",
        Quantity: 2,
        Price: 50.56 ,
        date: "2020/04/06",
        Status: "Accepted",
    },
    {
        userName: "Kaveen Hyacinth",
        ProductName: "Wood Craft",
        Quantity: 1,
        Price: 100.00 ,
        date: "2020/05/06",
        Status: "Rejected",
    },
]